#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate runtime capability rows and the feature matrix from one profile."""
import argparse
import json
import pathlib
import sys
from schema_inventory import Schema, inventory

ROOT = pathlib.Path(__file__).resolve().parent.parent


def outputs():
    old = Schema(ROOT / 'schema/scene-v1.xsd')
    new = Schema(ROOT / 'schema/scene-render-1.1.xsd')
    profile = json.loads((ROOT / 'schema/capabilities.json').read_text())
    rows = inventory(old, new, profile)
    header = ['/* Generated by tools/feature-matrix.py. Do not edit. */']
    document = ['# Feature matrix', '',
                'Generated from `schema/capabilities.json` and the versioned schemas',
                'by `tools/feature-matrix.py`. The same rows drive loader diagnostics.',
                'The 1.0 implementation and its test evidence are listed in',
                '[feature-tests.md](feature-tests.md). Unsupported contract entries',
                'fail at load time; they are never silently ignored.', '',
                '| Context / construct | Minimum version | Status |',
                '|---|---|---|']
    for kind, host, name, value, version, supported in rows:
        identity = ', '.join(json.dumps(s) for s in (host, name))
        header.append(f'    {{SR_CAP_{kind.upper()}, {identity},')
        header.append(f'     {json.dumps(value)}, {version}, {str(supported).lower()}}},')
        construct = name if kind in ('element', 'occurrence') else '@' + name
        if kind == 'occurrence':
            construct += ' occurrence > ' + value
        if kind in ('value', 'form'):
            construct += '=' + value
        document.append(f'| `{host}/{construct}` | {version / 10:.1f} | '
                        f'{"implemented" if supported else "unsupported"} |')
    return {'src/xml_capabilities_data.inc': '\n'.join(header) + '\n',
            'docs/feature-matrix.md': '\n'.join(document) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changed = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                changed.append(name)
        else:
            path.write_text(content)
    if changed:
        sys.stderr.write('stale capability artifacts: ' + ', '.join(changed) + '\n')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
